// flow-typed signature: 0e667456f5bd2bd11cbbd0657cc2713b
// flow-typed version: <<STUB>>/styletron-engine-atomic_v1.1.2/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styletron-engine-atomic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styletron-engine-atomic' 
{
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styletron-engine-atomic/dist/browser.es2015.es' 
{
  declare module.exports: any;
}

declare module 'styletron-engine-atomic/dist/browser.es2017.es' 
{
  declare module.exports: any;
}

declare module 'styletron-engine-atomic/dist/browser.es5.es' 
{
  declare module.exports: any;
}

declare module 'styletron-engine-atomic/dist/browser.es5' 
{
  declare module.exports: any;
}

declare module 'styletron-engine-atomic/dist/index.es' 
{
  declare module.exports: any;
}

declare module 'styletron-engine-atomic/dist/index' 
{
  declare module.exports: any;
}

declare module 'styletron-engine-atomic/src/__tests__/test.node' 
{
  declare module.exports: any;
}

declare module 'styletron-engine-atomic/src/cache' 
{
  declare module.exports: any;
}

declare module 'styletron-engine-atomic/src/client/__tests__/client.browser' 
{
  declare module.exports: any;
}

declare module 'styletron-engine-atomic/src/client/client' 
{
  declare module.exports: any;
}

declare module 'styletron-engine-atomic/src/css' 
{
  declare module.exports: any;
}

declare module 'styletron-engine-atomic/src/hyphenate-style-name' 
{
  declare module.exports: any;
}

declare module 'styletron-engine-atomic/src/index' 
{
  declare module.exports: any;
}

declare module 'styletron-engine-atomic/src/inject-style-prefixed' 
{
  declare module.exports: any;
}

declare module 'styletron-engine-atomic/src/sequential-id-generator' 
{
  declare module.exports: any;
}

declare module 'styletron-engine-atomic/src/server/__tests__/tests.node' 
{
  declare module.exports: any;
}

declare module 'styletron-engine-atomic/src/server/server' 
{
  declare module.exports: any;
}

declare module 'styletron-engine-atomic/src/sort-css-media-queries' 
{
  declare module.exports: any;
}

declare module 'styletron-engine-atomic/src/validate-keyframes-object' 
{
  declare module.exports: any;
}

declare module 'styletron-engine-atomic/src/validate-no-mixed-hand' 
{
  declare module.exports: any;
}

// Filename aliases
declare module 'styletron-engine-atomic/dist/browser.es2015.es.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/dist/browser.es2015.es'>;
}
declare module 'styletron-engine-atomic/dist/browser.es2017.es.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/dist/browser.es2017.es'>;
}
declare module 'styletron-engine-atomic/dist/browser.es5.es.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/dist/browser.es5.es'>;
}
declare module 'styletron-engine-atomic/dist/browser.es5.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/dist/browser.es5'>;
}
declare module 'styletron-engine-atomic/dist/index.es.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/dist/index.es'>;
}
declare module 'styletron-engine-atomic/dist/index.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/dist/index'>;
}
declare module 'styletron-engine-atomic/src/__tests__/test.node.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/src/__tests__/test.node'>;
}
declare module 'styletron-engine-atomic/src/cache.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/src/cache'>;
}
declare module 'styletron-engine-atomic/src/client/__tests__/client.browser.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/src/client/__tests__/client.browser'>;
}
declare module 'styletron-engine-atomic/src/client/client.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/src/client/client'>;
}
declare module 'styletron-engine-atomic/src/css.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/src/css'>;
}
declare module 'styletron-engine-atomic/src/hyphenate-style-name.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/src/hyphenate-style-name'>;
}
declare module 'styletron-engine-atomic/src/index.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/src/index'>;
}
declare module 'styletron-engine-atomic/src/inject-style-prefixed.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/src/inject-style-prefixed'>;
}
declare module 'styletron-engine-atomic/src/sequential-id-generator.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/src/sequential-id-generator'>;
}
declare module 'styletron-engine-atomic/src/server/__tests__/tests.node.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/src/server/__tests__/tests.node'>;
}
declare module 'styletron-engine-atomic/src/server/server.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/src/server/server'>;
}
declare module 'styletron-engine-atomic/src/sort-css-media-queries.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/src/sort-css-media-queries'>;
}
declare module 'styletron-engine-atomic/src/validate-keyframes-object.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/src/validate-keyframes-object'>;
}
declare module 'styletron-engine-atomic/src/validate-no-mixed-hand.js' 
{
  declare module.exports: $Exports<'styletron-engine-atomic/src/validate-no-mixed-hand'>;
}
