// flow-typed signature: 5c4eafffb2e5613aef3f9af29a9a8bdd
// flow-typed version: <<STUB>>/styletron-react_v5.0.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styletron-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styletron-react' 
{
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styletron-react/dist/browser.es2015.es' 
{
  declare module.exports: any;
}

declare module 'styletron-react/dist/browser.es2017.es' 
{
  declare module.exports: any;
}

declare module 'styletron-react/dist/browser.es5.es' 
{
  declare module.exports: any;
}

declare module 'styletron-react/dist/browser.es5' 
{
  declare module.exports: any;
}

declare module 'styletron-react/dist/index.es' 
{
  declare module.exports: any;
}

declare module 'styletron-react/dist/index' 
{
  declare module.exports: any;
}

declare module 'styletron-react/src/__tests__/tests.browser' 
{
  declare module.exports: any;
}

declare module 'styletron-react/src/dev-tool' 
{
  declare module.exports: any;
}

declare module 'styletron-react/src/index' 
{
  declare module.exports: any;
}

declare module 'styletron-react/src/types' 
{
  declare module.exports: any;
}

// Filename aliases
declare module 'styletron-react/dist/browser.es2015.es.js' 
{
  declare module.exports: $Exports<'styletron-react/dist/browser.es2015.es'>;
}
declare module 'styletron-react/dist/browser.es2017.es.js' 
{
  declare module.exports: $Exports<'styletron-react/dist/browser.es2017.es'>;
}
declare module 'styletron-react/dist/browser.es5.es.js' 
{
  declare module.exports: $Exports<'styletron-react/dist/browser.es5.es'>;
}
declare module 'styletron-react/dist/browser.es5.js' 
{
  declare module.exports: $Exports<'styletron-react/dist/browser.es5'>;
}
declare module 'styletron-react/dist/index.es.js' 
{
  declare module.exports: $Exports<'styletron-react/dist/index.es'>;
}
declare module 'styletron-react/dist/index.js' 
{
  declare module.exports: $Exports<'styletron-react/dist/index'>;
}
declare module 'styletron-react/src/__tests__/tests.browser.js' 
{
  declare module.exports: $Exports<'styletron-react/src/__tests__/tests.browser'>;
}
declare module 'styletron-react/src/dev-tool.js' 
{
  declare module.exports: $Exports<'styletron-react/src/dev-tool'>;
}
declare module 'styletron-react/src/index.js' 
{
  declare module.exports: $Exports<'styletron-react/src/index'>;
}
declare module 'styletron-react/src/types.js' 
{
  declare module.exports: $Exports<'styletron-react/src/types'>;
}
